name: Example Tests
# This workflow tests examples from the examples directory of this repo.

on:
  push:
    paths:
      - examples/**
  pull_request:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        directory: [
          basic-mini,
          basic,
          chrome-for-testing,
          chromium,
          firefox-esr,
          included-as-non-root
          ]
        os: [
          ubuntu-24.04-arm  # testing Linux/arm64 platform
          ]
        exclude:
          - os: ubuntu-24.04-arm
            directory: chrome-for-testing #browser not available for Linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Run test script (1st attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (2nd attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (2nd attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (3rd attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (4th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (5th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (6th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (7th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (8th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (9th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
        continue-on-error: true
      - name: Run test script (10th attempt)
        working-directory: examples/${{ matrix.directory }}
        run: ./scripts/test.sh
