name: npm seg fault
# This workflow tests examples from the examples directory of this repo.

on:
  workflow_dispatch:

jobs:
  example:
    strategy:
      fail-fast: false
      matrix:
        directory: [1,2,3,4,5,6]
        os: [ ubuntu-24.04-arm ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: vm info
        run: curl -s -H Metadata:true --noproxy "*" "http://169.254.169.254/metadata/instance?api-version=2021-02-01" | jq      
        
      - name: where is npm
        run: | 
          whereis npm
          
      - uses: actions/checkout@v4
      - name: Run test script
        #run: valgrind --leak-check=full  npm --version
        run: npm --version

      - name: chown
        if: always() #failure()
        run: sudo chown -R runner:runner /var/log* /var/lib/systemd
        
      - uses: actions/upload-artifact@v4
        if: always() #failure()
        with:
          name: logs-${{ matrix.directory }}-${{ matrix.os }}
          path: |
            /var/lib/systemd/coredump
            /var/log*
